# Generated by Django 4.1.5 on 2023-01-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skillsdata_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanddata',
            name='image',
            field=models.ImageField(upload_to='img/', verbose_name='Графика востребованности'),
        ),
    ]
